name: LootLlama
version: ${project.version}
main: me.halflove.lootllama.Main
api-version: '1.20'
authors: [ Halflove ]
description: Loot Llama Party for Vote Parties

commands:
  lootllama:
    aliases: [llama]
    usage: /Llama <arguments>